---
# Create Component directory
- name : "[create] Create Component Directory Path"
  file :
    path: "{{ DOWNLOAD_DIR }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true
  tags:
    - pre
    - create

# Create Component directory
- name : "[create] Create Component Directory Path"
  file :
    path: "{{ CONFIG_PATH }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true
  tags:
    - pre
    - create

- name : "[copy] Copy docker-compose.yml to Target Server"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ DOWNLOAD_DIR }}/docker-compose.yml"
    mode: 0755
  tags:
   - pre
   - copy

- name : "[copy] Copy redis.conf to Target Server"
  template:
    src: "redis.conf.j2"
    dest: "{{ CONFIG_PATH }}/redis.conf"
    mode: 0755
  tags:
   - pre
   - copy
   