---
# tasks file for vm-role
- name: "[pre] package Install"
  import_tasks: "tasks/pre-require.yml"

- name: "[install-docker] add "
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes


- name: "[install-docker] add docker package repository"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: true

- name: "[install-docker] install docker-ce"
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  become: true

- name: "[install-docker] install docker-ce-cli"
  apt:
    name: docker-ce-cli
    state: present
    update_cache: yes
  become: true

  
- name: "[install-docker] install containerd.io"
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  become: true

- name: "[install-docker] install docker-compose-plugin"
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes
  become: true

- name : "[install-docker] install docker-compose module"
  shell: |
    curl -SL https://github.com/docker/compose/releases/download/v2.14.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  become: true

- name : "[install-docker] docker-compose authorized enable"
  file: 
    path: /usr/local/bin/docker-compose
    mode: 0755
  become: true

- name : "[install-docker] add userMode -aG docker"
  shell: "usermod -aG docker {{ ansible_user }}"
  become: true