---
# Create Component directory
- name : "[create] Create Component Directory Path"
  file :
    path: "{{ DOWNLOAD_DIR }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true
  tags:
    - pre
    - create

- name : "[copy] Copy to docker-compose.yml"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ DOWNLOAD_DIR }}/docker-compose.yml"
    mode: 0755
  become: true
  tags:
   - pre
   - copy