---
# tasks file for k8s-role
- name: "[pre-require] install pre-require"
  import_tasks: "tasks/pre-require.yml"

- name: "[install-neuvector] install neuvector"
  include_tasks: "tasks/install-neuvector.yml"
