---
#Install pre-require

# Create Component directory
- name : "[pre] Create Component Directory Path"
  become: true
  file :
    path: "{{ DOWNLOAD_DIR }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags:
    - harbor-vm
    - harbor-vm-pre

- name : "[pre] Create Certi dir"
  become: true
  file :
    path: "{{ CERTI_DIR }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags:
    - harbor-vm
    - harbor-vm-pre

- name: "[install] Make log directory"
  become: true
  file:
    path: "{{ HARBOR_DIR }}/logs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags:
  - harbor-vm
  - harbor-vm-install