---
# tasks file for vm-role


# preRequire Set
- name: "install pre"
  import_tasks: "tasks/pre-require.yml"

- name: "[install] Download opensearch-{{ COMPONENT_VERSION }}-linux-x64.tar.gz"
  get_url:
    url: "https://artifacts.opensearch.org/releases/bundle/opensearch/{{ COMPONENT_VERSION }}/opensearch-{{ COMPONENT_VERSION }}-linux-x64.tar.gz"
    dest: "{{ DOWNLOAD_DIR }}"


- name: "[install] Unzip opensearch-{{ COMPONENT_VERSION }}-linux-x64.tar.gz"
  unarchive : 
    src: "{{ DOWNLOAD_DIR }}/opensearch-{{ COMPONENT_VERSION }}-linux-x64.tar.gz"
    dest: "{{ DOWNLOAD_DIR }}"
    remote_src: yes

- name: "[install] Add Bashrc OPENSEARCH_JAVA_HOME"
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: "export OPENSEARCH_JAVA_HOME={{ OPENSEARCH_DIR }}/jdk"

- name: "[install] Apply OPENSEARCH_JAVA_HOME"
  shell: source /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash

- name: "[install] Make script directory"
  file:
    path: "{{ DOWNLOAD_DIR }}/scripts"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: "[install] Link config directory"
  file:
    src: "{{ OPENSEARCH_CONFIG_DIR }}"
    dest: "{{ DOWNLOAD_DIR }}/config"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true
    
- name: "[install] Link log directory"
  file:
    src: "{{ OPENSEARCH_LOG_DIR }}"
    dest: "{{ DOWNLOAD_DIR }}/logs"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: "[install] Copy config"
  template:
    src: "opensearch.yml.j2"
    dest: "{{ DOWNLOAD_DIR }}/opensearch-{{ COMPONENT_VERSION }}/config/opensearch.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: "[install] Add systemctl opensearch.service"
  template:
    src: "opensearch.service.j2"
    dest: "/etc/systemd/system/opensearch.service"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  become: true

- name: "[install] copy templates scripts"
  template:
    src: "scripts/{{ item }}.j2"
    dest: "{{ DOWNLOAD_DIR }}/scripts/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - restart_binary_opensearch.sh
    - restart_service_opensearch.sh
    - start_binary_opensearch.sh
    - start_service_opensearch.sh
    - stop_binary_opensearch.sh
    - stop_service_opensearch.sh
  tags:
    - script
